[general]
live_config_reload = true

[window]
decorations = "Buttonless"
dynamic_padding = false
padding = { x = 18, y = 16 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
size = 18.0
